In [1]:
import json, requests
import re
import pandas as pd
import numpy as np
from pymongo import ASCENDING, DESCENDING
from pymongo import MongoClient
import os
from dotenv import load_dotenv
load_dotenv()
from folium import Map, Marker, Icon, FeatureGroup, LayerControl, Choropleth
from folium.plugins import HeatMap

import os
from dotenv import load_dotenv
load_dotenv()

def getApi(endpoint, queryParams={}):
    url = f"https://api.github.com{endpoint}"

    apiKey = os.getenv("ID")
    apiKey = os.getenv("SECRET")
    if not apiKey:
        raise ValueError("Please setup the GITHUB_APIKEY env variable")
    headers = {
        "Authorization": f"token {apiKey}"
    }
    
    res = requests.get(url, headers=headers, params=queryParams)
    print(res.url)
    return res.json()

import json, requests
import os
from dotenv import load_dotenv
load_dotenv()
url = 'https://api.foursquare.com/v2/venues/explore'

params = dict(
client_id=os.getenv("ID"),
client_secret=os.getenv("SECRET"),
v='20200601',
near="Chicago, IL",
locale="es", 
query='vegan'
)
resp = requests.get(url=url, params=params)
data = json.loads(resp.text)

In [2]:
dbName = "companies"
mongodbURL = f"mongodb://localhost/{dbName}"

client = MongoClient(mongodbURL, connectTimeoutMS=2000, serverSelectionTimeoutMS=2000)
db = client.get_database()

In [3]:
companies=list(db.companies.find({'category_code':{'$in':[re.compile(r"game(?i)"),re.compile(r"design(?i)")]}},{"name":1, "offices":1, "_id":0}))

/home/jorge/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Flags not at the start of the expression 'game(?i)'
  """Entry point for launching an IPython kernel.
/home/jorge/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: Flags not at the start of the expression 'design(?i)'
  """Entry point for launching an IPython kernel.

In [4]:
df = pd.DataFrame(list(companies))

In [5]:
df

                       name                                            offices
0                   Flektor  [{'description': None, 'address1': '8536 Natio...
1                      Lala  [{'description': 'Lala Headquarters', 'address...
2                     Joost  [{'description': '', 'address1': '100 5th Ave ...
3                  Babelgum  [{'description': '', 'address1': '', 'address2...
4                   Sparter  [{'description': None, 'address1': None, 'addr...
...                     ...                                                ...
1082  Symposium Productions                                                 []
1083              Rev Media  [{'description': 'HQ', 'address1': '', 'addres...
1084             Fictionaut  [{'description': 'New York', 'address1': '32-1...
1085             Tiny Speck  [{'description': '', 'address1': '163 Hastings...
1086            My TV Shows  [{'description': 'Lisbon Office', 'address1': ...

[1087 rows x 2 columns]

In [6]:
offices = df.explode("offices").apply(lambda e: e.offices,axis=1,result_type="expand")
offices

,description,address1,address2,zip_code,city,state_code,country_code,latitude,longitude
0,None,"8536 National Blvd, Suite A",None,90232,Culver City,CA,USA,34.025958,-118.379768
1,Lala Headquarters,209 Hamilton Ave,Suite #200,94301,Palo Alto,CA,USA,37.451151,-122.154369
2,,100 5th Ave Fl 6,,10011-6903,New York,NY,USA,40.746497,-74.009447
3,,,,,London,None,GBR,53.344104,-6.267494
4,None,None,None,None,None,None,USA,37.090240,-95.712891
...,...,...,...,...,...,...,...,...,...
1083,HQ,,,,Dallas,TX,USA,NaN,NaN
1084,New York,32-14 42nd St,,11103,Astoria,NY,USA,40.759795,-73.916127
1084,Houston,2208 Colquitt,,77098,Houston,TX,USA,29.735462,-95.413243
1085,,163 Hastings St W,,BC V6B 1H5,Vancouver,None,CAN,49.282455,-123.109217
1086,Lisbon Office,Rua RosÃƒÂ¡lia de Castro,,1700,Lisbon,None,PRT,38.752367,-9.146221

In [7]:
clean_offices = pd.concat([df[["name"]], offices], axis=1)
clean_offices

,name,description,address1,address2,zip_code,city,state_code,country_code,latitude,longitude
0,Flektor,None,"8536 National Blvd, Suite A",None,90232,Culver City,CA,USA,34.025958,-118.379768
1,Lala,Lala Headquarters,209 Hamilton Ave,Suite #200,94301,Palo Alto,CA,USA,37.451151,-122.154369
2,Joost,,100 5th Ave Fl 6,,10011-6903,New York,NY,USA,40.746497,-74.009447
3,Babelgum,,,,,London,None,GBR,53.344104,-6.267494
4,Sparter,None,None,None,None,None,None,USA,37.090240,-95.712891
...,...,...,...,...,...,...,...,...,...,...
1083,Rev Media,HQ,,,,Dallas,TX,USA,NaN,NaN
1084,Fictionaut,New York,32-14 42nd St,,11103,Astoria,NY,USA,40.759795,-73.916127
1084,Fictionaut,Houston,2208 Colquitt,,77098,Houston,TX,USA,29.735462,-95.413243
1085,Tiny Speck,,163 Hastings St W,,BC V6B 1H5,Vancouver,None,CAN,49.282455,-123.109217
1086,My TV Shows,Lisbon Office,Rua RosÃƒÂ¡lia de Castro,,1700,Lisbon,None,PRT,38.752367,-9.146221

In [8]:
def transformToGeoPoint(s):
    if np.isnan(s.latitude) or np.isnan(s.longitude):
        return None
    return {
        "type":"Point",
        "coordinates":[s.longitude, s.latitude]
    }
    

clean_offices["geopoint"] = clean_offices.apply(transformToGeoPoint, axis=1)

In [9]:
clean_offices.head()

,name,description,address1,address2,zip_code,city,state_code,country_code,latitude,longitude,geopoint
0,Flektor,None,"8536 National Blvd, Suite A",None,90232,Culver City,CA,USA,34.025958,-118.379768,"{'type': 'Point', 'coordinates': [-118.379768,..."
1,Lala,Lala Headquarters,209 Hamilton Ave,Suite #200,94301,Palo Alto,CA,USA,37.451151,-122.154369,"{'type': 'Point', 'coordinates': [-122.154369,..."
2,Joost,,100 5th Ave Fl 6,,10011-6903,New York,NY,USA,40.746497,-74.009447,"{'type': 'Point', 'coordinates': [-74.0094471,..."
3,Babelgum,,,,,London,None,GBR,53.344104,-6.267494,"{'type': 'Point', 'coordinates': [-6.267494, 5..."
4,Sparter,None,None,None,None,None,None,USA,37.090240,-95.712891,"{'type': 'Point', 'coordinates': [-95.712891, ..."

In [10]:
clean_offices= clean_offices[clean_offices["city"] == "San Francisco"]

In [11]:
clean_offices =clean_offices.dropna(subset=["latitude", "longitude"], how='all')
clean_offices["latitude"].isnull().value_counts()

False    50
Name: latitude, dtype: int64

In [12]:
clean_offices["city"].value_counts()

San Francisco    50
Name: city, dtype: int64

In [13]:
clean_offices.to_json("offices.json",orient="records")

# Starbucks

import os
from dotenv import load_dotenv
load_dotenv()

def getFromGithub(endpoint, queryParams={}):
    url = f"https://api.github.com{endpoint}"

    apiKey = os.getenv("GITHUB_APIKEY")
    if not apiKey:
        raise ValueError("Please setup the GITHUB_APIKEY env variable")
    headers = {
        "Authorization": f"token {apiKey}"
    }
    
    res = requests.get(url, headers=headers, params=queryParams)
    print(res.url)
    return res.json()

In [14]:
def geocode(address):
    res = requests.get(f"https://geocode.xyz/{address}", params={"json":1})
    data = res.json()
    return {
        "type":"Point",
        "coordinates":[float(data["longt"]),float(data["latt"])]
    }

In [15]:
center_SF = geocode("San Francisco, CA")
center_SF

{'type': 'Point', 'coordinates': [-122.45712, 37.78986]}

In [16]:
def getQuery(info, queryParams={}):
    url = 'https://api.foursquare.com/v2/venues/explore'
    params = dict(
    client_id=os.getenv("ID"),
    client_secret=os.getenv("SECRET"),
    v='20200623',
    ll="37.78986,-122.45712",
    query=info,
    radius=6000,
    limit=500
    )
    resp = requests.get(url=url, params=params)
    return json.loads(resp.text)

In [17]:
def getId(idcategory, radio):
    url = 'https://api.foursquare.com/v2/venues/explore'
    params = dict(
    client_id=os.getenv("ID"),
    client_secret=os.getenv("SECRET"),
    v='20200623',
    ll="37.78986,-122.45712" ,
    categoryId=idcategory,
    radius=radio,
    limit=500
    )
    resp = requests.get(url=url, params=params)
    return json.loads(resp.text)

In [18]:
starbucks_SF = getQuery("starbucks")

In [19]:
vegan_SF = getId("4bf58dd8d48988d1d3941735", 6000)

In [20]:
basketball_SF= getId("4bf58dd8d48988d18b941735", 10000)

In [39]:
party_SF= getQuery("4bf58dd8d48988d11f941735", 20000)

In [22]:
starbucks_SF_dict=[]
for i in list(range(len(starbucks_SF["response"]["groups"][0]["items"]))):
        
            starbucks_SF_dict.append({
        "name": starbucks_SF["response"]["groups"][0]["items"][i]["venue"]["name"],
        "state_code": starbucks_SF["response"]["groups"][0]["items"][i]["venue"]["location"]["state"],
        "country_code": starbucks_SF["response"]["groups"][0]["items"][i]["venue"]["location"]["country"],
        "latitude": starbucks_SF["response"]["groups"][0]["items"][i]["venue"]["location"]["lat"],
        "longitude": starbucks_SF["response"]["groups"][0]["items"][i]["venue"]["location"]["lng"]
    })

In [23]:
vegan_SF_dict=[]
for i in list(range(len(vegan_SF["response"]["groups"][0]["items"]))):
        
            vegan_SF_dict.append({
        "name": vegan_SF["response"]["groups"][0]["items"][i]["venue"]["name"],
        "state_code": vegan_SF["response"]["groups"][0]["items"][i]["venue"]["location"]["state"],
        "country_code": vegan_SF["response"]["groups"][0]["items"][i]["venue"]["location"]["country"],
        "latitude": vegan_SF["response"]["groups"][0]["items"][i]["venue"]["location"]["lat"],
        "longitude": vegan_SF["response"]["groups"][0]["items"][i]["venue"]["location"]["lng"]
    })

In [24]:
basketball_SF_dict=[]
for i in list(range(len(basketball_SF["response"]["groups"][0]["items"]))):
        
            basketball_SF_dict.append({
        "name": basketball_SF["response"]["groups"][0]["items"][i]["venue"]["name"],
        "state_code": basketball_SF["response"]["groups"][0]["items"][i]["venue"]["location"]["state"],
        "country_code": basketball_SF["response"]["groups"][0]["items"][i]["venue"]["location"]["country"],
        "latitude": basketball_SF["response"]["groups"][0]["items"][i]["venue"]["location"]["lat"],
        "longitude": basketball_SF["response"]["groups"][0]["items"][i]["venue"]["location"]["lng"]
    })

In [40]:
party_SF_dict=[]
for i in list(range(len(party_SF["response"]["groups"][0]["items"]))):
        
            party_SF_dict.append({
        "name": party_SF["response"]["groups"][0]["items"][i]["venue"]["name"],
        "state_code": party_SF["response"]["groups"][0]["items"][i]["venue"]["location"]["state"],
        "country_code": party_SF["response"]["groups"][0]["items"][i]["venue"]["location"]["country"],
        "latitude": party_SF["response"]["groups"][0]["items"][i]["venue"]["location"]["lat"],
        "longitude": party_SF["response"]["groups"][0]["items"][i]["venue"]["location"]["lng"]
    })

In [25]:
starbucks = pd.DataFrame(starbucks_SF_dict)
starbucks["geopoint"] = starbucks.apply(transformToGeoPoint, axis=1)
starbucks.to_json("starbucks.json",orient="records")

In [26]:
vegan_restaurants = pd.DataFrame(vegan_SF_dict)
vegan_restaurants["geopoint"] = vegan_restaurants.apply(transformToGeoPoint, axis=1)
vegan_restaurants.to_json("vegan.json",orient="records")

In [27]:
basketball = pd.DataFrame(basketball_SF_dict)
basketball["geopoint"] = basketball.apply(transformToGeoPoint, axis=1)
basketball.to_json("basketball.json",orient="records")

In [41]:
party = pd.DataFrame(party_SF_dict)
party["geopoint"] = party.apply(transformToGeoPoint, axis=1)
party.to_json("party.json",orient="records")

In [28]:
def geoQueryNear(point,radius=10000):
    return {
        "geopoint":{
            "$near": {
                "$geometry": point,
                "$maxDistance": radius,
                "$minDistance": 0
            }
        }
    }

In [115]:
near_offices_starbucks=[]
for i in range(len(starbucks)):
    q=(db.offices.find(geoQueryNear(starbucks.iloc[i].geopoint, radius=100),{"_id":0,"company_id":0}))
    near_offices_starbucks.append(list(q))
near_offices_starbucks=[x for i in near_offices_starbucks for x in i]
offices_starbucks=pd.DataFrame(near_offices_starbucks)
offices_starbucks.to_json("offices_starbucks.json",orient="records")

In [116]:
near_offices_vegan=[]
for i in range(len(vegan_restaurants)):
    q=(db.offices_starbucks.find(geoQueryNear(vegan_restaurants.iloc[i].geopoint, radius=100),{"_id":0,"company_id":0}))
    near_offices_vegan.append(list(q))
near_offices_vegan=[x for i in near_offices_vegan for x in i]
offices_vegan=pd.DataFrame(near_offices_vegan)
offices_vegan = offices_vegan.drop_duplicates(subset=["latitude","longitude"], keep="first")
offices_vegan.to_json("offices_vegan.json",orient="records")

In [51]:
near_offices_party=[]
for i in range(len(party)):
    q=(db.offices_vegan.find(geoQueryNear(party.iloc[i].geopoint, radius=1000),{"_id":0,"company_id":0}))
    near_offices_party.append(list(q))
near_offices_party=[x for i in near_offices_party for x in i]
offices_party=pd.DataFrame(near_offices_party)
offices_party = offices_party.drop_duplicates(subset=["latitude","longitude"], keep="first")
offices_party.to_json("offices_party.json",orient="records")

In [52]:
offices_party

,name,description,address1,address2,zip_code,city,state_code,country_code,latitude,longitude,geopoint
0,Exent,Premium Services,685 Market Street,Suite 560,94105,San Francisco,CA,USA,37.787646,-122.402759,"{'type': 'Point', 'coordinates': [-122.402759,..."
1,hi5,,55 Second Street,Suite 400,94105,San Francisco,CA,USA,37.788668,-122.400558,"{'type': 'Point', 'coordinates': [-122.400558,..."
2,Serious Business,,580 Market Street,#600,94104,San Francisco,CA,USA,37.789321,-122.401362,"{'type': 'Point', 'coordinates': [-122.4013624..."
3,PlayFirst,HQ,160 Spear St,Suite 1300,94105,San Francisco,CA,USA,37.790346,-122.401850,"{'type': 'Point', 'coordinates': [-122.40185, ..."

In [127]:
near_offices_basketball=[]
for i in range(len(basketball)):
    q=(db.offices_vegan.find(geoQueryNear(basketball.iloc[i].geopoint, radius=500),{"_id":0,"company_id":0}))
    near_offices_basketball.append(list(q))
near_offices_basketball=[x for i in near_offices_basketball for x in i]
offices_basketball=pd.DataFrame(near_offices_basketball)
offices_basketball = offices_basketball.drop_duplicates(subset=["latitude","longitude"], keep="first")
offices_basketball.to_json("offices_basketball.json",orient="records")

In [166]:
near_starbucks=[]
for i in range(len(offices_basketball)):
    q=(db.starbucks.find(geoQueryNear(offices_basketball.iloc[i].geopoint, radius=100),{"_id":0,"company_id":0}))
    near_starbucks.append(list(q))
near_starbucks=[x for i in near_starbucks for x in i]
off_starbucks=pd.DataFrame(near_starbucks)
off_starbucks = off_starbucks.drop_duplicates(subset=["latitude","longitude"], keep="first")

In [178]:
near_vegan=[]
for i in range(len(offices_basketball)):
    q=(db.vegan.find(geoQueryNear(offices_basketball.iloc[i].geopoint, radius=100),{"_id":0,"company_id":0}))
    near_vegan.append(list(q))
near_vegan=[x for i in near_vegan for x in i]
off_vegan=pd.DataFrame(near_vegan)
off_vegan = off_vegan.drop_duplicates(subset=["latitude","longitude"], keep="first")

In [188]:
near_basketball=[]
for i in range(len(offices_basketball)):
    q=(db.basketball.find(geoQueryNear(offices_basketball.iloc[3].geopoint, radius=500),{"_id":0,"company_id":0}))
    near_basketball.append(list(q))
near_basketball=[x for i in near_basketball for x in i]
off_basketball=pd.DataFrame(near_basketball)
off_basketball = off_basketball.drop_duplicates(subset=["latitude","longitude"], keep="first")

In [192]:
final = pd.concat([offices_basketball, off_starbucks, off_vegan, off_basketball])
final

,name,description,address1,address2,zip_code,city,state_code,country_code,latitude,longitude,geopoint
0,Exent,Premium Services,685 Market Street,Suite 560,94105,San Francisco,CA,USA,37.787646,-122.402759,"{'type': 'Point', 'coordinates': [-122.402759,..."
1,Serious Business,,580 Market Street,#600,94104,San Francisco,CA,USA,37.789321,-122.401362,"{'type': 'Point', 'coordinates': [-122.4013624..."
2,hi5,,55 Second Street,Suite 400,94105,San Francisco,CA,USA,37.788668,-122.400558,"{'type': 'Point', 'coordinates': [-122.400558,..."
3,PlayFirst,HQ,160 Spear St,Suite 1300,94105,San Francisco,CA,USA,37.790346,-122.401850,"{'type': 'Point', 'coordinates': [-122.40185, ..."
0,Starbucks,NaN,NaN,NaN,NaN,NaN,CA,United States,37.787360,-122.403180,"{'type': 'Point', 'coordinates': [-122.40318, ..."
1,Starbucks,NaN,NaN,NaN,NaN,NaN,CA,United States,37.789594,-122.402032,"{'type': 'Point', 'coordinates': [-122.402032,..."
2,Starbucks,NaN,NaN,NaN,NaN,NaN,CA,United States,37.788792,-122.400710,"{'type': 'Point', 'coordinates': [-122.4007102..."
4,Starbucks,NaN,NaN,NaN,NaN,NaN,CA,United States,37.787902,-122.401144,"{'type': 'Point', 'coordinates': [-122.4011438..."
5,Starbucks,NaN,NaN,NaN,NaN,NaN,CA,United States,37.790070,-122.402083,"{'type': 'Point', 'coordinates': [-122.4020826..."
0,Ginto Izakaya Japonaise,NaN,NaN,NaN,NaN,NaN,CA,United States,37.788313,-122.402916,"{'type': 'Point', 'coordinates': [-122.402916,..."
1,Dosa Brothers,NaN,NaN,NaN,NaN,NaN,CA,United States,37.789021,-122.401848,"{'type': 'Point', 'coordinates': [-122.4018479..."
2,Sunrise Deli,NaN,NaN,NaN,NaN,NaN,CA,United States,37.788611,-122.400532,"{'type': 'Point', 'coordinates': [-122.4005322..."
3,WeTheTrillions.,NaN,NaN,NaN,NaN,NaN,CA,United States,37.790158,-122.402439,"{'type': 'Point', 'coordinates': [-122.402439,..."
0,Equinox Sports Club San Francisco,NaN,NaN,NaN,NaN,NaN,CA,United States,37.786649,-122.404568,"{'type': 'Point', 'coordinates': [-122.4045675..."

In [207]:
m = Map(location=[37.779026,-122.419906],zoom_start=12)

for i, row in offices_basketball.iterrows():
        icon = Icon(
                color="blue",
                prefix="fa",
                icon="trophy")
        Marker(
        location=row[["latitude","longitude"]],
        icon=icon
    ).add_to(m)    
        
for i, row in off_vegan.iterrows():
        icon = Icon(
                color="green",
                prefix="fa",
                icon="trophy")
        Marker(
        location=row[["latitude","longitude"]],
        icon=icon
    ).add_to(m)    
        
for i, row in off_basketball.iterrows():
        icon = Icon(
                color="orange",
                prefix="fa",
                icon="trophy")
        Marker(
        location=row[["latitude","longitude"]],
        icon=icon
    ).add_to(m)   
        
for i, row in off_starbucks.iterrows():
        icon = Icon(
                color="black",
                prefix="fa",
                icon="trophy")
        Marker(
        location=row[["latitude","longitude"]],
        icon=icon
    ).add_to(m)   
        
        icon = Icon(
                color="red",
                prefix="fa",
                icon="trophy")
        Marker(
        location=[37.78874648132847,-122.40199864051569],
        icon=icon
    ).add_to(m) 

        
m

In [42]:
m = Map(location=[37.779026,-122.419906],zoom_start=12)

for i, row in party.iterrows():
        icon = Icon(
                color="blue",
                prefix="fa",
                icon="trophy")
        Marker(
        location=row[["latitude","longitude"]],
        icon=icon
    ).add_to(m)    
        

        
m

In [193]:
import math

x = 0.0
y = 0.0
z = 0.0

for i, coord in final.iterrows():
    latitude = math.radians(coord.latitude)
    longitude = math.radians(coord.longitude)

    x += math.cos(latitude) * math.cos(longitude)
    y += math.cos(latitude) * math.sin(longitude)
    z += math.sin(latitude)

total = len(final)

x = x / total
y = y / total
z = z / total

central_longitude = math.atan2(y, x)
central_square_root = math.sqrt(x * x + y * y)
central_latitude = math.atan2(z, central_square_root)

mean_location = {
    'latitude': math.degrees(central_latitude),
    'longitude': math.degrees(central_longitude)
    }

In [ ]:
mean_location

In [194]:
mean_location

{'latitude': 37.78874648132847, 'longitude': -122.40199864051569}

In [199]:
m = Map(location=[37.779026,-122.419906],zoom_start=12)

for i, row in offices_basketball.iterrows():
        icon = Icon(
                color="blue",
                prefix="fa",
                icon="trophy")
        Marker(
        location=row[["latitude","longitude"]],
        icon=icon
    ).add_to(m)    
        
print(row[["latitude","longitude"]])

latitude     37.7903
longitude   -122.402
Name: 3, dtype: object

In [60]:
vegan_SF["response"]["groups"][0]["items"][0]["venue"]["name"]
vegan_SF["response"]["groups"][0]["items"][0]["venue"]["location"]["address"]
vegan_SF["response"]["groups"][0]["items"][0]["venue"]["location"]["postalCode"]
vegan_SF["response"]["groups"][0]["items"][0]["venue"]["location"]["city"]
vegan_SF["response"]["groups"][0]["items"][0]["venue"]["location"]["state"]
vegan_SF["response"]["groups"][0]["items"][0]["venue"]["location"]["country"]
vegan_SF["response"]["groups"][0]["items"][0]["venue"]["location"]["lat"]
vegan_SF["response"]["groups"][0]["items"][0]["venue"]["location"]["lng"]

-122.4324404

In [61]:
a={
        "name": vegan_SF["response"]["groups"][0]["items"][0]["venue"]["name"],
        "adress": vegan_SF["response"]["groups"][0]["items"][0]["venue"]["location"]["address"],
        "zip_code": vegan_SF["response"]["groups"][0]["items"][0]["venue"]["location"]["postalCode"],
        "city": vegan_SF["response"]["groups"][0]["items"][0]["venue"]["location"]["city"],
        "state_code": vegan_SF["response"]["groups"][0]["items"][0]["venue"]["location"]["state"],
        "country_code": vegan_SF["response"]["groups"][0]["items"][0]["venue"]["location"]["country"],
        "latitude": vegan_SF["response"]["groups"][0]["items"][0]["venue"]["location"]["lat"],
        "longitude": vegan_SF["response"]["groups"][0]["items"][0]["venue"]["location"]["lng"]
    }